History:
  # %% is a line break
  displayname: "&6%sanctiontype% §e%player% %date%"
  lore: "&6By : &e%banner% %%&6Reason : &e%reason% %%&6Duration : &e%duration% %%&6Expiration : &e%expiration% %%&6Expired : &e%expired%"
  isExpired: "&aYes"
  isNotExpired: "&cNo"
  sanctiontype:
    ban: "&cBan"
    tempban: "&cTempban"
    banip: "&cBanIP"
    mute: "&9Mute"
    tempmute: "&9Tempmute"
    kick: "&eKick"
    unknown: "&7Unknown"