# Available YAML and MYSQL(need to edit credentials)
# Be careful with the storage method option, if you type it wrong, the plugin will automatically switch to YAML
storage:
  method: YAML
  # If you want to use MYSQL, you need to edit the credentials here
  # The plugin will create a database called reapersanction with all of the tables needed in it
  # If your credentials are wrong, the plugin will automatically shutdown
  MYSQL:
    host: 127.0.0.1
    port: 3306
    username: root
    password: root
History:
  # %% is a line break
  displayname: "&6%sanctiontype% §e%player% %date%"
  lore: "&6By : &e%banner% %%&6Reason : &e%reason% %%&6Duration : &e%duration% %%&6Expiration : &e%expiration% %%&6Expired : &e%expired%"
  isExpired: "&aYes"
  isNotExpired: "&cNo"
  sanctiontype:
    ban: "&cBan"
    tempban: "&cTempban"
    banip: "&cBanIP"
    mute: "&9Mute"
    tempmute: "&9Tempmute"
    kick: "&eKick"
    unknown: "&7Unknown"

Discord:
  active: false
  webhook_url:
  tempmute:
    desc: "**Author ·** ``%author%``\\n**Target ·** ``%target%``\\n**Reason ·** ``%reason%``\\n**SanctionType ·** ``TempMute``\\n**Duration ·** ``%duration%``\\n**Server ·** ``%server_name%``"
    thumbnail: "https://minotar.net/avatar/%target%/100.png"
    author:
      name: "%author%"
      icon_url: "https://minotar.net/avatar/%author%/100.png"
      url: "https://namemc.com/profile/%author%"
    color: "#29ad91"
  tempban:
    desc: "**Author ·** ``%author%``\\n**Target ·** ``%target%``\\n**Reason ·** ``%reason%``\\n**SanctionType ·** ``TempBan``\\n**Duration ·** ``%duration%``\\n**Server ·** ``%server_name%``"
    thumbnail: "https://minotar.net/avatar/%target%/100.png"
    author:
      name: "%author%"
      icon_url: "https://minotar.net/avatar/%author%/100.png"
      url: "https://namemc.com/profile/%author%"
    color: "#29ad91"
  ban:
    desc: "**Author ·** ``%author%``\\n**Target ·** ``%target%``\\n**Reason ·** ``%reason%``\\n**SanctionType ·** ``Ban``\\n**Server ·** ``%server_name%``"
    thumbnail: "https://minotar.net/avatar/%target%/100.png"
    author:
      name: "%author%"
      icon_url: "https://minotar.net/avatar/%author%/100.png"
      url: "https://namemc.com/profile/%author%"
    color: "#29ad91"
  ban_ip:
    desc: "**Author ·** ``%author%``\\n**Target ·** ``%target%``\\n**Reason ·** ``%reason%``\\n**SanctionType ·** ``BanIP``\\n**Server ·** ``%server_name%``"
    thumbnail: "https://minotar.net/avatar/%target%/100.png"
    author:
      name: "%author%"
      icon_url: "https://minotar.net/avatar/%author%/100.png"
      url: "https://namemc.com/profile/%author%"
    color: "#29ad91"
  kick:
    desc: "**Author ·** ``%author%``\\n**Target ·** ``%target%``\\n**Reason ·** ``%reason%``\\n**SanctionType ·** ``Kick``\\n**Server ·** ``%server_name%``"
    thumbnail: "https://minotar.net/avatar/%target%/100.png"
    author:
      name: "%author%"
      icon_url: "https://minotar.net/avatar/%author%/100.png"
      url: "https://namemc.com/profile/%author%"
    color: "#29ad91"
  mute:
    desc: "**Author ·** ``%author%``\\n**Target ·** ``%target%``\\n**Reason ·** ``%reason%``\\n**SanctionType ·** ``Mute``\\n**Server ·** ``%server_name%``"
    thumbnail: "https://minotar.net/avatar/%target%/100.png"
    author:
      name: "%author%"
      icon_url: "https://minotar.net/avatar/%author%/100.png"
      url: "https://namemc.com/profile/%author%"
    color: "#29ad91"
  unmute:
    desc: "**Author ·** ``%author%``\\n**Target ·** ``%target%``\\n**Reason ·** ``%reason%``\\n**SanctionType ·** ``Unmute``\\n**Server ·** ``%server_name%``"
    thumbnail: "https://minotar.net/avatar/%target%/100.png"
    author:
      name: "%author%"
      icon_url: "https://minotar.net/avatar/%author%/100.png"
      url: "https://namemc.com/profile/%author%"
    color: "#29ad91"
  unban:
    desc: "**Author ·** ``%author%``\\n**Target ·** ``%target%``\\n**Reason ·** ``%reason%``\\n**SanctionType ·** ``Unban``\\n**Server ·** ``%server_name%``"
    thumbnail: "https://minotar.net/avatar/%target%/100.png"
    author:
      name: "%author%"
      icon_url: "https://minotar.net/avatar/%author%/100.png"
      url: "https://namemc.com/profile/%author%"
    color: "#29ad91"
  report:
    desc: "**Author ·** ``%author%``\\n**Target ·** ``%target%``\\n**Reason ·** ``%reason%``\\n**Server ·** ``%server_name%``"
    thumbnail: "https://minotar.net/avatar/%target%/100.png"
    author:
      name: "%author%"
      icon_url: "https://minotar.net/avatar/%author%/100.png"
      url: "https://namemc.com/profile/%author%"
    color: "#29ad91"