#Config version 1.5.0
IP:
  ShowIpForAdmin: true
  ShowIpForMod: true

TimeZone: Europe/Paris

# Available YAML and MYSQL(need to edit credentials)
# Be careful with the storage method option, if you type it wrong, the plugin will automatically switch to YAML
storage:
  method: YAML
  # If you want to use MYSQL, you need to edit the credentials here
  # The plugin will create a database called reapersanction with all of the tables needed in it
  # If your credentials are wrong, the plugin will automatically shutdown
  MYSQL:
    host: 127.0.0.1
    port: 3306
    username: root
    password: root

FillInventoryWithGlassPane: false

#Use \n to go to the next line (max ~25)
BanIp:
  lines: "&cConnection refused \n \n&4You are permantly ip banned from this server \n\n&6Date of ban : &e%date% \n&6By : &e%banner% \n&6Reason : &e%reason%"

Ban:
  lines: "&cConnection refused \n \n&4You are permantly banned from this server \n\n&6Date of ban : &e%date% \n&6By : &e%banner% \n&6Reason : &e%reason%"

TempBan:
  lines: "&cConnection refused \n \n&4You are temp banned from this server \n\n&6Date of ban : &e%date% \n&6By: &e%banner% \n&6Expiration : &e%expiration% \n&6Reason : &e%reason% \n&6Duration : &e%duration%"

Kick:
  lines: "&cConnection stopped \n \n&4You have been kicked from this server \n\n&6Date of kick : &e%date% \n&6By : &e%banner% \n&6Reason : &e%reason%"

History:
  GoBackDoor: "&6Go Back"
  # %% is a line break
  displayname: "&6%sanctiontype% §e%player% %date%"
  lore: "&6By : &e%banner% %%&6Reason : &e%reason% %%&6Duration : &e%duration% %%&6Expiration : &e%expiration% %%&6Expired : &e%expired%"
  isExpired: "&aYes"
  isNotExpired: "&cNo"
  sanctiontype:
    ban: "&cBan"
    tempban: "&cTempban"
    banip: "&cBanIP"
    mute: "&9Mute"
    tempmute: "&9Tempmute"
    kick: "&eKick"
    unknown: "&7Unknown"
Vanish:
  Enabled: true
  #Change gamemode when enter in vanish mode
  #Gamemode 0 to 3
  ChangeGamemode: true
  Gamemode: 2
  #Gamemode after going out of the vanish
  ExitGamemode: true
  ExGamemode: 0
  Fly: true

Discord:
  active: false
  webhook_url:
  tempmute:
    desc: "**Author ·** ``%author%``\\n**Target ·** ``%target%``\\n**Reason ·** ``%reason%``\\n**SanctionType ·** ``TempMute``\\n**Duration ·** ``%duration%``\\n**Server ·** ``%server_name%``"
    thumbnail: "https://minotar.net/avatar/%target%/100.png"
    author:
      name: "%author%"
      icon_url: "https://minotar.net/avatar/%author%/100.png"
      url: "https://namemc.com/profile/%author%"
    color: "#29ad91"
  tempban:
    desc: "**Author ·** ``%author%``\\n**Target ·** ``%target%``\\n**Reason ·** ``%reason%``\\n**SanctionType ·** ``TempBan``\\n**Duration ·** ``%duration%``\\n**Server ·** ``%server_name%``"
    thumbnail: "https://minotar.net/avatar/%target%/100.png"
    author:
      name: "%author%"
      icon_url: "https://minotar.net/avatar/%author%/100.png"
      url: "https://namemc.com/profile/%author%"
    color: "#29ad91"
  ban:
    desc: "**Author ·** ``%author%``\\n**Target ·** ``%target%``\\n**Reason ·** ``%reason%``\\n**SanctionType ·** ``Ban``\\n**Server ·** ``%server_name%``"
    thumbnail: "https://minotar.net/avatar/%target%/100.png"
    author:
      name: "%author%"
      icon_url: "https://minotar.net/avatar/%author%/100.png"
      url: "https://namemc.com/profile/%author%"
    color: "#29ad91"
  ban_ip:
    desc: "**Author ·** ``%author%``\\n**Target ·** ``%target%``\\n**Reason ·** ``%reason%``\\n**SanctionType ·** ``BanIP``\\n**Server ·** ``%server_name%``"
    thumbnail: "https://minotar.net/avatar/%target%/100.png"
    author:
      name: "%author%"
      icon_url: "https://minotar.net/avatar/%author%/100.png"
      url: "https://namemc.com/profile/%author%"
    color: "#29ad91"
  kick:
    desc: "**Author ·** ``%author%``\\n**Target ·** ``%target%``\\n**Reason ·** ``%reason%``\\n**SanctionType ·** ``Kick``\\n**Server ·** ``%server_name%``"
    thumbnail: "https://minotar.net/avatar/%target%/100.png"
    author:
      name: "%author%"
      icon_url: "https://minotar.net/avatar/%author%/100.png"
      url: "https://namemc.com/profile/%author%"
    color: "#29ad91"
  mute:
    desc: "**Author ·** ``%author%``\\n**Target ·** ``%target%``\\n**Reason ·** ``%reason%``\\n**SanctionType ·** ``Mute``\\n**Server ·** ``%server_name%``"
    thumbnail: "https://minotar.net/avatar/%target%/100.png"
    author:
      name: "%author%"
      icon_url: "https://minotar.net/avatar/%author%/100.png"
      url: "https://namemc.com/profile/%author%"
    color: "#29ad91"
  unmute:
    desc: "**Author ·** ``%author%``\\n**Target ·** ``%target%``\\n**Reason ·** ``%reason%``\\n**SanctionType ·** ``Unmute``\\n**Server ·** ``%server_name%``"
    thumbnail: "https://minotar.net/avatar/%target%/100.png"
    author:
      name: "%author%"
      icon_url: "https://minotar.net/avatar/%author%/100.png"
      url: "https://namemc.com/profile/%author%"
    color: "#29ad91"
  unban:
    desc: "**Author ·** ``%author%``\\n**Target ·** ``%target%``\\n**Reason ·** ``%reason%``\\n**SanctionType ·** ``Unban``\\n**Server ·** ``%server_name%``"
    thumbnail: "https://minotar.net/avatar/%target%/100.png"
    author:
      name: "%author%"
      icon_url: "https://minotar.net/avatar/%author%/100.png"
      url: "https://namemc.com/profile/%author%"
    color: "#29ad91"
  report:
    desc: "**Author ·** ``%author%``\\n**Target ·** ``%target%``\\n**Reason ·** ``%reason%``\\n**Server ·** ``%server_name%``"
    thumbnail: "https://minotar.net/avatar/%target%/100.png"
    author:
      name: "%author%"
      icon_url: "https://minotar.net/avatar/%author%/100.png"
      url: "https://namemc.com/profile/%author%"
    color: "#29ad91"