#Config version 1.3.0
IP:
  ShowIpForAdmin: true
  ShowIpForMod: true

# Available YAML and MYSQL(need to edit credentials)
# Be careful with the storage method option, if you type it wrong, the plugin will automatically switch to YAML
storage:
  method: YAML
  # If you want to use MYSQL, you need to edit the credentials here
  # The plugin will create a database called reapersanction with all of the tables needed in it
  # If your credentials are wrong, the plugin will automatically shutdown
  MYSQL:
    host: 127.0.0.1
    port: 3306
    username: root
    password: root

FillInventoryWithGlassPane: false

#Use \n to go to the next line (max ~25)
BanIp:
  lines: "&cConnection refused \n \n&4You are permantly ip banned from this server \n\n&6Date of ban : &e%date% \n&6By : &e%banner% \n&6Reason : &e%reason%"

Ban:
  lines: "&cConnection refused \n \n&4You are permantly banned from this server \n\n&6Date of ban : &e%date% \n&6By : &e%banner% \n&6Reason : &e%reason%"

TempBan:
  lines: "&cConnection refused \n \n&4You are temp banned from this server \n\n&6Date of ban : &e%date% \n&6By: &e%banner% \n&6Expiration : &e%expiration% \n&6Reason : &e%reason% \n&6Duration : &e%duration%"

History:
  displayname: "&6%sanctiontype% §e%player% %date%"
  lore: "&6By : &e%banner% %%&6Reason : &e%reason% %%&6Duration : &e%duration% %%&6Expiration : &e%expiration%"
Vanish:
  Enabled: true
  #Change gamemode when enter in vanish mode
  #Gamemode 0 to 3
  ChangeGamemode: true
  Gamemode: 2
  #Gamemode after going out of the vanish
  ExitGamemode: true
  ExGamemode: 0
  Fly: true
Report:
  Enabled: true
  Reason:
    grass: "&6Incorrect skin/name"
    DiamondSword: "&6Hacks"
    apple: "&6Cross team"
    beacon: "&6Others"
Menu:
  RsMenu:
    GrassBlock: "&6Mutes"
    DiamondSword: "&6Bans"
    SkullLore:
      line1: "&eIP: %ip%"
      line2: "&eDisplay name: %displayname%"
      #You can't add more line for the moment
    Anvil: "&6Ban-ip"
    Paper: "&6Unbans and Unmutes"
    Barrier: "&4No Permission"
    GoBackDoor: "&6Go Back"
    History: "&6History"
  #You need to add s for second or m for minute or d for day or w for week or y for year
  Mutes:
    Bow:
      Reason: "Spam"
      Duration: "20min"
    DiamondSword:
      Reason: "Flood"
      Duration: "20min"
    Anvil:
      Reason: "Insults"
      Duration: "30min"
    RedstoneBlock:
      Reason: "Provocation"
      Duration: "30min"
    ActivatorRail:
      Reason: "Incitement to crimine"
      Duration: "1hour"
    ArmorStand:
      Reason: "Sanction evading"
      Duration: "30min"
    Compass:
      Reason: "Pub"
      Duration: "1day"
    FlintAndSteel:
      Reason: "Threat"
      Duration: "1day"
  Bans:
    DiamondSword:
      Reason: "Killaura"
      Duration: "7day"
    WoodSword:
      Reason: "CPS"
      Duration: "7day"
    Feather:
      Reason: "Fly"
      Duration: "7day"
    IronBoots:
      Reason: "Anti knockback"
      Duration: "7day"
    GoldAxe:
      Reason: "Reach"
      Duration: "7day"
    ArmorStand:
      Reason: "Others hacks"
      Duration: "7day"
    Tnt:
      Reason: "Incorrect player name"
      Duration: "10year"
    Leather:
      Reason: "Incorrect skin"
      Duration: "1day"
    DiamondChestPlate:
      Reason: "Other"
      Duration: "7day"
    Dirt:
      Reason: "Incorrect build"
      Duration: "5day"
  Banip:
    NameTag:
      Reason: "Usurpation"
    ClayBall:
      Reason: "Multiple account"