name: ReaperSanction
version: 1.3.1
author: Farmeurimmo
main: main.java.fr.farmeurimmo.reapersanction.ReaperSanction
website: https://reaper.farmeurimmo.fr/reapersanction
description: A plugin to punish players with simple gui
commands:
  rs:
    description: Open sanctiongui
    aliases: [ sanction, reapersanction ]
    permission: reapersanction
  rsadmin:
    description: Admin command
    permission: reapersanction.rsadmin
  report:
    description: Report command
    permission: reapersanction.report
  vanish:
    description: Vanish command
    aliases: [ v ]
    permission: reapersanction.vanish
  ban:
    permission: reapersanction.ban
  tempban:
    permission: reapersanction.tempban
  ban-ip:
    permission: reapersanction.ban-ip
  mute:
    permission: reapersanction.mute
  unmute:
    permission: reapersanction.unmute
  tempmute:
    permission: reapersanction.tempmute
  unban:
    permission: reapersanction.unban
  history:
    permission: reapersanction.history