name: ReaperSanction
version: 2.0.0-RC1
author: Farmeurimmo
main: fr.farmeurimmo.reapersanction.spigot.ReaperSanction
website: https://farmeurimmo.fr/projects/reapersanction
description: A plugin to punish players with simple gui
commands:
  rs:
    description: Open sanctiongui
    aliases: [ sanction, reapersanction ]
    permission: reapersanction
  rsadmin:
    description: Admin command
    permission: reapersanction.rsadmin
  report:
    description: Report command
    permission: reapersanction.report
  vanish:
    description: Vanish command
    aliases: [ v ]
    permission: reapersanction.vanish
  tempban:
    permission: reapersanction.tempban
  ban:
    permission: reapersanction.ban
  ban-ip:
    permission: reapersanction.ban-ip
  mute:
    permission: reapersanction.mute
  unmute:
    permission: reapersanction.unmute
  tempmute:
    permission: reapersanction.tempmute
  unban:
    permission: reapersanction.unban
  history:
    permission: reapersanction.history
  kick:
    permission: reapersanction.kick